
    var orgs = [
        {"name": "kurniarvind/meetupmedia-App",
         "type": "repo",
         "link": "https://meetupmedia-19c32.firebaseapp.com"},
        /*{"name": "wasdev",
          "type": "org",
          "link": "http://wasdev.github.io/"},*/
        {"name": "kurniarvind/templatestore-App",
          "type": "repo",
          "link": "https://templatestore-7e379.firebaseapp.com"},
        {"name": "kurniarvind/mycontacts-App",
          "type": "repo",
          "link": "https://mycontacts-990e5.firebaseapp.com"},
        {"name": "kurniarvind/facebookconnect-App",
          "type": "repo",
          "link": "https://socialconnect-e6b28.firebaseapp.com"},
        {"name": "kurniarvind/userauth-App",
          "type": "repo",
          "link": "https://userauth-app.herokuapp.com/"},
        {"name": "kurniarvind/GalPhoto-App",
          "type": "repo"},
        {"name": "kurniarvind/pnChat-App",
          "type": "repo"},
        {"name": "kurniarvind/knowledgebase-App",
          "type": "repo"},
        {"name": "kurniarvind/kurniarvind.github.io",
          "type": "repo"},
    ];
